spring.application.name: send-kubemq
kubemq.address: kubemq-cluster-grpc:50000
server.port: 8081
logging.pattern.console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){faint}%n"