apiVersion: apps/v1
kind: Deployment
metadata:
  name: send-kubemq
  namespace: kubemq
  labels:
    app: send-kubemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: send-kubemq
  template:
    metadata:
      labels:
        app: send-kubemq
    spec:
      containers:
        - name: send-kubemq
          image: send-kubemq
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: send-kubemq
  namespace: kubemq
  labels:
    app: send-kubemq
spec:
  ports:
    - port: 8081
      protocol: TCP
  selector:
    app: send-kubemq
  type: NodePort